// Small embedded word list. ANSWERS are the pool we pick the day's word from —
// curated to be common, recognisable, and audience-friendly. VALID_GUESSES is the
// superset of words a player is allowed to submit as a guess (Wordle behaves the
// same way: the answer pool is smaller than the legal-guess pool).

export const ANSWERS: string[] = [
  'apple', 'beach', 'brave', 'bread', 'brick', 'bring', 'brown', 'build',
  'chair', 'cheer', 'chess', 'cloud', 'coast', 'crisp', 'crown', 'dance',
  'dream', 'drink', 'eagle', 'earth', 'enjoy', 'fancy', 'feast', 'field',
  'first', 'flame', 'flash', 'flute', 'fresh', 'fruit', 'glass', 'globe',
  'grape', 'green', 'happy', 'heart', 'house', 'jolly', 'juice', 'lemon',
  'light', 'lucky', 'magic', 'mango', 'merry', 'music', 'night', 'noble',
  'ocean', 'olive', 'paint', 'peach', 'piano', 'pizza', 'plant', 'pride',
  'queen', 'quick', 'quiet', 'quilt', 'radio', 'rapid', 'reset', 'river',
  'royal', 'sharp', 'shine', 'silky', 'skill', 'sleep', 'smile', 'smoke',
  'spark', 'speed', 'spice', 'sport', 'stone', 'storm', 'sugar', 'sunny',
  'sweet', 'swift', 'table', 'taste', 'thank', 'tiger', 'tower', 'train',
  'treat', 'trust', 'unite', 'value', 'video', 'water', 'wheel', 'world',
];

// Common 5-letter words a player might try as a guess. Combined with ANSWERS to
// form the full legal-guess dictionary.
const EXTRA_GUESSES: string[] = [
  'about', 'above', 'after', 'again', 'agent', 'alert', 'alien', 'align',
  'alive', 'allow', 'alone', 'along', 'amber', 'angle', 'angry', 'apart',
  'apply', 'arena', 'argue', 'arise', 'arose', 'array', 'aside', 'asset',
  'audio', 'avoid', 'awake', 'award', 'aware', 'badge', 'baker', 'basic',
  'basin', 'baton', 'beard', 'beast', 'begin', 'being', 'below', 'bench',
  'birth', 'black', 'blade', 'blame', 'blank', 'blast', 'blaze', 'bleed',
  'blend', 'bless', 'blind', 'block', 'blood', 'bloom', 'blown', 'blues',
  'blunt', 'board', 'boast', 'bonus', 'boost', 'booth', 'bound', 'brain',
  'brand', 'brash', 'brass', 'bravo', 'breed', 'brief', 'brisk', 'broad',
  'broke', 'broth', 'brush', 'buddy', 'buggy', 'built', 'bunch', 'burnt',
  'burst', 'cabin', 'cable', 'candy', 'canoe', 'cargo', 'carry', 'catch',
  'cause', 'cease', 'chalk', 'champ', 'chant', 'chaos', 'charm', 'chart',
  'chase', 'cheap', 'check', 'chess', 'chest', 'chief', 'child', 'chill',
  'chime', 'china', 'chips', 'choir', 'choke', 'chose', 'chuck', 'chunk',
  'cider', 'cigar', 'civic', 'civil', 'claim', 'clamp', 'clash', 'clasp',
  'class', 'clean', 'clear', 'clerk', 'click', 'cliff', 'climb', 'cling',
  'clock', 'clone', 'close', 'cloth', 'clown', 'clued', 'clump', 'coach',
  'cobra', 'cocoa', 'colon', 'color', 'comet', 'comic', 'count', 'court',
  'cover', 'crack', 'craft', 'cramp', 'crane', 'crash', 'crate', 'crawl',
  'crazy', 'cream', 'creek', 'creep', 'crept', 'crest', 'cried', 'crime',
  'croak', 'crook', 'cross', 'crowd', 'crude', 'cruel', 'crumb', 'crush',
  'crust', 'curve', 'cycle', 'daily', 'dairy', 'daisy', 'dandy', 'dated',
  'dealt', 'death', 'debit', 'debug', 'decal', 'decay', 'decoy', 'delta',
  'demon', 'depot', 'depth', 'derby', 'devil', 'diary', 'diner', 'dirty',
  'disco', 'ditch', 'diver', 'dodge', 'doing', 'donor', 'doubt', 'dough',
  'dowel', 'dozen', 'draft', 'drain', 'drama', 'drank', 'drawn', 'dread',
  'dress', 'dried', 'drift', 'drill', 'drive', 'drone', 'drove', 'drown',
  'druid', 'drunk', 'dwarf', 'eager', 'eaten', 'eight', 'elbow', 'elder',
  'elite', 'email', 'empty', 'enact', 'ended', 'enemy', 'enter', 'entry',
  'equal', 'erase', 'error', 'essay', 'event', 'every', 'exact', 'exile',
  'exist', 'extra', 'fable', 'faced', 'faint', 'fairy', 'faith', 'false',
  'fault', 'favor', 'feign', 'feral', 'fetch', 'fever', 'fewer', 'fiber',
  'fifth', 'fifty', 'fight', 'final', 'fired', 'fixed', 'fjord', 'flair',
  'flake', 'flank', 'flask', 'fleet', 'flesh', 'flick', 'flier', 'fling',
  'flint', 'flirt', 'float', 'flock', 'flood', 'floor', 'flour', 'fluff',
  'fluid', 'flung', 'flush', 'focal', 'focus', 'folks', 'force', 'forge',
  'forte', 'forth', 'forty', 'forum', 'found', 'frame', 'frank', 'fraud',
  'freak', 'freed', 'front', 'frost', 'frown', 'froze', 'fudge', 'fully',
  'funny', 'gamer', 'gamma', 'gauge', 'genie', 'genre', 'ghost', 'giant',
  'girth', 'given', 'giver', 'glade', 'gland', 'glare', 'gleam', 'glide',
  'glint', 'gloom', 'glory', 'gloss', 'glove', 'going', 'gourd', 'grace',
  'grade', 'graft', 'grain', 'grand', 'grant', 'graph', 'grasp', 'grass',
  'grate', 'grave', 'gravy', 'great', 'greed', 'greet', 'grief', 'grill',
  'grime', 'grind', 'gripe', 'groan', 'groom', 'gross', 'group', 'grout',
  'grove', 'grown', 'gruff', 'guard', 'guess', 'guest', 'guide', 'guild',
  'guilt', 'haiku', 'haunt', 'haven', 'hazel', 'heart', 'heavy', 'hedge',
  'hello', 'hence', 'heron', 'honey', 'honor', 'horse', 'hotel', 'hover',
  'human', 'humor', 'hunch', 'hurry', 'icing', 'ideal', 'idiom', 'idiot',
  'image', 'imply', 'index', 'inert', 'inner', 'input', 'irony', 'issue',
  'ivory', 'jelly', 'jewel', 'joint', 'judge', 'juicy', 'jumbo', 'jumpy',
  'karma', 'kayak', 'knack', 'knead', 'kneel', 'knelt', 'knife', 'knock',
  'known', 'koala', 'label', 'labor', 'laden', 'lance', 'large', 'laser',
  'later', 'laugh', 'layer', 'leach', 'leafy', 'leaky', 'learn', 'lease',
  'least', 'leave', 'ledge', 'level', 'lever', 'lilac', 'limit', 'linen',
  'liner', 'linen', 'lithe', 'liver', 'loath', 'lobby', 'local', 'lodge',
  'lofty', 'logic', 'loose', 'lorry', 'loser', 'lover', 'lower', 'loyal',
  'lunar', 'lunch', 'lurch', 'lying', 'macro', 'madly', 'major', 'maker',
  'mango', 'maple', 'march', 'marsh', 'mason', 'match', 'mayor', 'meant',
  'medal', 'media', 'melon', 'mercy', 'metal', 'meter', 'might', 'miner',
  'minor', 'minus', 'mixer', 'model', 'modem', 'moist', 'money', 'month',
  'moose', 'moral', 'morph', 'motel', 'motor', 'mount', 'mourn', 'mouse',
  'mouth', 'movie', 'mover', 'mower', 'mucky', 'muddy', 'mummy', 'mural',
  'naive', 'nasal', 'nasty', 'naval', 'needy', 'nerdy', 'nerve', 'never',
  'newer', 'newly', 'niche', 'niece', 'ninja', 'ninth', 'noise', 'noisy',
  'north', 'novel', 'nurse', 'nylon', 'oasis', 'ocean', 'octet', 'offer',
  'often', 'older', 'olive', 'onion', 'onset', 'opera', 'orbit', 'order',
  'organ', 'other', 'otter', 'ought', 'outdo', 'outer', 'owner', 'panel',
  'panic', 'paper', 'parka', 'parry', 'party', 'pasta', 'patch', 'pause',
  'payer', 'peace', 'peach', 'pearl', 'pedal', 'penny', 'perch', 'piano',
  'piece', 'pilot', 'pinch', 'pitch', 'pivot', 'pixel', 'pixie', 'place',
  'plain', 'plait', 'plane', 'plank', 'plant', 'plate', 'plead', 'pleat',
  'plier', 'pluck', 'plumb', 'plume', 'plump', 'plush', 'point', 'poker',
  'polar', 'porch', 'pouch', 'pound', 'power', 'press', 'price', 'prick',
  'pride', 'prime', 'primp', 'print', 'prior', 'prism', 'prize', 'probe',
  'prone', 'proof', 'prose', 'proud', 'prove', 'prowl', 'proxy', 'prune',
  'pulse', 'punch', 'pupil', 'puppy', 'purge', 'purse', 'pushy', 'quack',
  'quail', 'quake', 'qualm', 'quark', 'quart', 'queer', 'query', 'quest',
  'quest', 'queue', 'quirk', 'quite', 'quote', 'rabid', 'racer', 'radar',
  'raise', 'rally', 'ranch', 'range', 'raspy', 'ratio', 'raven', 'react',
  'ready', 'realm', 'rebel', 'refer', 'reign', 'relax', 'relic', 'remit',
  'renal', 'renew', 'reply', 'rerun', 'reuse', 'rhyme', 'ridge', 'rifle',
  'right', 'rigor', 'rinse', 'risky', 'rival', 'roast', 'robin', 'robot',
  'rocky', 'roger', 'rogue', 'roost', 'rough', 'round', 'route', 'rowdy',
  'royal', 'ruler', 'rural', 'sable', 'sadly', 'salad', 'salsa', 'sandy',
  'satin', 'sauce', 'saucy', 'sauna', 'scale', 'scalp', 'scaly', 'scamp',
  'scan',  'scare', 'scarf', 'scary', 'scent', 'scoop', 'scope', 'score',
  'scorn', 'scour', 'scout', 'scowl', 'scram', 'scrap', 'screw', 'scrub',
  'scuba', 'sedan', 'seedy', 'sense', 'serve', 'setup', 'seven', 'sever',
  'shack', 'shade', 'shady', 'shaft', 'shake', 'shaky', 'shale', 'shall',
  'shame', 'shape', 'share', 'shark', 'sharp', 'shave', 'shawl', 'shear',
  'sheen', 'sheep', 'sheer', 'sheet', 'shelf', 'shell', 'shied', 'shift',
  'shine', 'shiny', 'shire', 'shirk', 'shirt', 'shoal', 'shock', 'shone',
  'shook', 'shoot', 'shore', 'short', 'shown', 'shred', 'shrew', 'shrub',
  'shrug', 'sight', 'silly', 'since', 'sinew', 'singe', 'siren', 'sissy',
  'sixth', 'sixty', 'skate', 'skier', 'skimp', 'skirt', 'skull', 'skunk',
  'slack', 'slain', 'slang', 'slant', 'slash', 'slate', 'slave', 'sleek',
  'sleep', 'sleet', 'slept', 'slice', 'slick', 'slide', 'slime', 'slimy',
  'sling', 'slip',  'slope', 'slosh', 'sloth', 'slump', 'slung', 'slurp',
  'small', 'smart', 'smash', 'smear', 'smell', 'smelt', 'smock', 'snack',
  'snail', 'snake', 'sneak', 'sneer', 'snipe', 'snore', 'snort', 'snout',
  'snowy', 'sober', 'sock',  'soggy', 'solar', 'solid', 'solve', 'sonar',
  'sonic', 'sorry', 'sound', 'south', 'space', 'spade', 'spank', 'spare',
  'spark', 'spawn', 'speak', 'spear', 'speed', 'spell', 'spelt', 'spend',
  'spent', 'sperm', 'spice', 'spicy', 'spied', 'spike', 'spiky', 'spill',
  'spilt', 'spine', 'spiny', 'spire', 'split', 'spoil', 'spoke', 'spoof',
  'spool', 'spoon', 'sport', 'spout', 'spray', 'spree', 'sprig', 'spunk',
  'spurn', 'spurt', 'squad', 'stack', 'staff', 'stage', 'staid', 'stain',
  'stair', 'stake', 'stale', 'stalk', 'stall', 'stamp', 'stand', 'stank',
  'stare', 'stark', 'start', 'stash', 'state', 'stave', 'stead', 'steak',
  'steal', 'steam', 'steed', 'steel', 'steep', 'steer', 'stein', 'stern',
  'stick', 'stiff', 'still', 'sting', 'stink', 'stint', 'stock', 'stoic',
  'stole', 'stomp', 'stood', 'stool', 'stoop', 'store', 'stork', 'storm',
  'story', 'stout', 'stove', 'strap', 'straw', 'stray', 'strip', 'strut',
  'stuck', 'study', 'stuff', 'stump', 'stung', 'stunt', 'style', 'suite',
  'super', 'surge', 'sushi', 'swamp', 'swarm', 'swear', 'sweat', 'sweep',
  'sweet', 'swell', 'swept', 'swirl', 'sworn', 'syrup', 'tacky', 'taken',
  'taker', 'tally', 'tango', 'taper', 'tardy', 'tasty', 'taunt', 'teach',
  'teary', 'teeth', 'tempo', 'tense', 'tepid', 'terms', 'thank', 'theft',
  'their', 'theme', 'there', 'these', 'thick', 'thief', 'thigh', 'thing',
  'think', 'third', 'thong', 'thorn', 'those', 'three', 'threw', 'throb',
  'throw', 'thumb', 'thump', 'tibia', 'tidal', 'tiger', 'tight', 'tilde',
  'timer', 'timid', 'tinge', 'tipsy', 'titan', 'today', 'token', 'tonal',
  'tonic', 'topic', 'torch', 'total', 'touch', 'tough', 'toxic', 'trace',
  'track', 'trade', 'trail', 'train', 'trait', 'tramp', 'trash', 'tread',
  'treat', 'trend', 'triad', 'trial', 'tribe', 'trick', 'tried', 'tripe',
  'trite', 'troll', 'troop', 'trope', 'trout', 'truce', 'truck', 'truly',
  'trump', 'trunk', 'truss', 'truth', 'tubby', 'tuner', 'tunic', 'turbo',
  'tutor', 'twang', 'tweak', 'tweed', 'twice', 'twine', 'twist', 'tying',
  'udder', 'ultra', 'uncle', 'under', 'undid', 'undue', 'unfit', 'unify',
  'union', 'unity', 'until', 'unwed', 'upper', 'upset', 'urban', 'usage',
  'usher', 'using', 'usual', 'utter', 'vague', 'valid', 'valor', 'valve',
  'vapor', 'vault', 'vegan', 'venom', 'venue', 'verge', 'verse', 'verso',
  'vigor', 'villa', 'vinyl', 'viper', 'viral', 'virus', 'visit', 'vital',
  'vivid', 'vixen', 'vocal', 'vodka', 'vogue', 'voice', 'voila', 'voted',
  'voter', 'vowel', 'wacky', 'wafer', 'wager', 'wagon', 'waist', 'waive',
  'waltz', 'warty', 'waste', 'watch', 'wavey', 'weary', 'weave', 'wedge',
  'weedy', 'weigh', 'weird', 'whack', 'whale', 'wharf', 'wheat', 'where',
  'which', 'while', 'whine', 'whiny', 'whirl', 'whisk', 'white', 'whole',
  'whose', 'widen', 'wider', 'widow', 'width', 'wield', 'wight', 'wimpy',
  'wince', 'winch', 'windy', 'wiper', 'wired', 'wiser', 'wispy', 'witch',
  'witty', 'woken', 'woman', 'women', 'wooed', 'wooer', 'woozy', 'wordy',
  'worry', 'worse', 'worst', 'worth', 'would', 'wound', 'woven', 'wrack',
  'wrath', 'wreak', 'wreck', 'wrest', 'wring', 'wrist', 'write', 'wrong',
  'wrote', 'wrung', 'yacht', 'yearn', 'yeast', 'yield', 'young', 'youth',
  'zebra', 'zesty', 'zoned',
];

// Build the legal-guess set. Lowercased for case-insensitive lookup.
export const VALID_GUESSES: Set<string> = new Set(
  [...ANSWERS, ...EXTRA_GUESSES].map((w) => w.toLowerCase()),
);

export function pickRandomAnswer(): string {
  const index = Math.floor(Math.random() * ANSWERS.length);
  return ANSWERS[index]!.toLowerCase();
}

export function isValidGuess(word: string): boolean {
  return VALID_GUESSES.has(word.toLowerCase());
}
